import os
import requests
from openai import OpenAI
import uuid
import re

def generate_script(description: str, media_type: str) -> str:
    """Generate a short TikTok/Reel script based on technical description."""
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    
    media_context = "a clinical video" if media_type == 'video' else "before and after photos"
    prompt = f"""
    Act as an engaging, professional dentist creating a TikTok/Reel.
    You are showing {media_context} of a dental procedure.
    Technical Description: {description}
    
    Prompt: Escribe un guion corto de 15-20 segundos con voz en off que traduzca esta descripción técnica en una explicación atractiva y fácil de entender para el paciente.
    Mantenlo profesional pero accesible. SACA SÓLO el texto hablado, sin acciones, sin títulos, sin emojis o hashtags.
    IMPORTANTE: El guion DEBE estar SIEMPRE en español de Chile (chilenismos moderados, tono cercano pero profesional).
    """
    
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a professional dentist AI assistant creating content for patients."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7,
        max_tokens=150
    )
    
    return response.choices[0].message.content.strip()

def pre_process_dental_script(text: str):
    # 1. Normalización de Siglas y Números (Erre-dos, I-A)
    replacements = {
        r"\bR2\b": "erre dos",
        r"\bIA\b": "i a",
        r"\bAI\b": "i a",
        r"(\d+)\s?MB": r"\1 megas",
        r"Reel": "rril",
        r"post": "poust"
    }
    
    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)

    # 2. Ortografía Fonética para acentos latinos
    # Forzamos tildes donde la IA suele equivocarse
    phonetic_fixes = {
        "dental": "dentál",
        "incrustación": "incrustasión",
        "resina": "ressina",
        "odontólogo": "odonto-logo"
    }
    
    for word, fixed in phonetic_fixes.items():
        text = text.replace(word, fixed)

    # 3. Puntuación Exagerada para "Respiración"
    # Cambiamos puntos por puntos suspensivos y comas para dar pausas
    text = text.replace(". ", "... ")
    text = text.replace(", ", ",,, ") 
    
    return text


def generate_voiceover(text: str, output_dir: str) -> str:
    """Generate voiceover using local Kokoro TTS."""
    try:
        from kokoro import KPipeline
        import soundfile as sf
        import os
        import uuid
        
        # 1. APLICAR EL AJUSTE FONÉTICO ANTES DE GENERAR
        # Esto transforma "dental" en "dentál" y añade las pausas ,,,
        pre_process_text = pre_process_dental_script(text)

        # Initialize pipeline for Spanish
        pipeline = KPipeline(lang_code='es')
        
        # Choose voice (e.g. af_bella adapted to Spanish) and speed
        voice = 'af_bella' #'am_michael'
        speed = 1.15  #1.1

        # KPipeline generator yields (graphemes, phonemes, audio)
        generator = pipeline(pre_process_text, voice=voice, speed=speed, split_pattern=r'\n+')
        
        audio_segments = []
        for i, (gs, ps, audio) in enumerate(generator):
            if audio is not None:
                audio_segments.append(audio)
        
        if not audio_segments:
            raise Exception("No audio was generated by Kokoro.")
            
        import numpy as np
        final_audio = np.concatenate(audio_segments)
        
        os.makedirs(output_dir, exist_ok=True)
        file_path = os.path.join(output_dir, f"voiceover_{uuid.uuid4().hex[:8]}.wav")
        
        # Save audio using soundfile
        # Kokoro usually outputs at 24000 Hz sample rate
        sf.write(file_path, final_audio, 24000)
        
        return file_path
        
    except Exception as e:
        print(f"ERROR: Local TTS generation failed: {str(e)}")
        import traceback
        traceback.print_exc()
        raise Exception(f"Failed to generate local TTS: {str(e)}")

def generate_instagram_copy(description: str, script: str) -> str:
    """Generate an Instagram post copy with emojis and hashtags based on the clinical description and script."""
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    
    prompt = f"""
    Act as a professional and engaging community manager for a dental clinic in Chile.
    Based on the following script from a recent procedure video and the original technical description, write an engaging Instagram caption.
    
    Technical Description: {description}
    Video Script: {script}
    
    The caption must be in Chilean Spanish, informative but friendly.
    Include relevant emojis and 5-7 relevant hashtags at the end.
    Output ONLY the text for the caption.
    """
    
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are an expert social media manager for dental clinics."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7,
        max_tokens=250
    )
    
    return response.choices[0].message.content.strip()
